import { chunk } from "lodash"

export type TextToSpeechConfig = { label: string, locale: string, gender: string, voice: string }
export const TextToSpeechConfigs: TextToSpeechConfig[] = chunk([
    'Arabic (Egypt)', 'ar-EG', 'Female', 'ar-EG-SalmaNeural',
    'Arabic (Egypt)', 'ar-EG', 'Male', 'ar-EG-ShakirNeural',
    'Arabic (Saudi Arabia)', 'ar-SA', 'Female', 'ar-SA-ZariyahNeural',
    'Arabic (Saudi Arabia)', 'ar-SA', 'Male', 'ar-SA-HamedNeural',
    'Bulgarian (Bulgaria)', 'bg-BG', 'Female', 'bg-BG-KalinaNeural',
    'Bulgarian (Bulgaria)', 'bg-BG', 'Male', 'bg-BG-BorislavNeural',
    'Catalan (Spain)', 'ca-ES', 'Female', 'ca-ES-AlbaNeural',
    'Catalan (Spain)', 'ca-ES', 'Female', 'ca-ES-JoanaNeural',
    'Catalan (Spain)', 'ca-ES', 'Male', 'ca-ES-EnricNeural',
    'Chinese (Mandarin,Simplified,)', 'zh-CN', 'Male', 'zh-CN-YunyangNeural',
    'Chinese (Mandarin,Simplified,)', 'zh-CN', 'Female', 'zh-CN-XiaoxiaoNeural',
    'Chinese (Mandarin,Simplified,)', 'zh-CN', 'Female', 'zh-CN-XiaoyouNeural',
    'Chinese (Cantonese,Traditional,)', 'zh-HK', 'Female', 'zh-HK-HiuGaaiNeural',
    'Chinese (Cantonese,Traditional,)', 'zh-HK', 'Female', 'zh-HK-HiuMaanNeural',
    'Chinese (Cantonese,Traditional,)', 'zh-HK', 'Male', 'zh-HK-WanLungNeural',
    'Chinese (Taiwanese Mandarin)', 'zh-TW', 'Female', 'zh-TW-HsiaoChenNeural',
    'Chinese (Taiwanese Mandarin)', 'zh-TW', 'Female', 'zh-TW-HsiaoYuNeural',
    'Chinese (Taiwanese Mandarin)', 'zh-TW', 'Male', 'zh-TW-YunJheNeural',
    'Chinese (Mandarin,Simplified,)', 'zh-CN', 'Male', 'zh-CN-YunyeNeural',
    'Croatian (Croatia)', 'hr-HR', 'Female', 'hr-HR-GabrijelaNeural',
    'Croatian (Croatia)', 'hr-HR', 'Male', 'hr-HR-SreckoNeural',
    'Czech (Czech)', 'cs-CZ', 'Female', 'cs-CZ-VlastaNeural',
    'Czech (Czech)', 'cs-CZ', 'Male', 'cs-CZ-AntoninNeural',
    'Danish (Denmark)', 'da-DK', 'Female', 'da-DK-ChristelNeural',
    'Danish (Denmark)', 'da-DK', 'Male', 'da-DK-JeppeNeural',
    'Dutch (Belgium)', 'nl-BE', 'Female', 'nl-BE-DenaNeural',
    'Dutch (Belgium)', 'nl-BE', 'Male', 'nl-BE-ArnaudNeural',
    'Dutch (Netherlands)', 'nl-NL', 'Female', 'nl-NL-ColetteNeural',
    'Dutch (Netherlands)', 'nl-NL', 'Female', 'nl-NL-FennaNeural',
    'Dutch (Netherlands)', 'nl-NL', 'Male', 'nl-NL-MaartenNeural',
    'English (Australia)', 'en-AU', 'Female', 'en-AU-NatashaNeural',
    'English (Australia)', 'en-AU', 'Male', 'en-AU-WilliamNeural',
    'English (Canada)', 'en-CA', 'Female', 'en-CA-ClaraNeural',
    'English (Canada)', 'en-CA', 'Male', 'en-CA-LiamNeural',
    'English (India)', 'en-IN', 'Female', 'en-IN-NeerjaNeural',
    'English (India)', 'en-IN', 'Male', 'en-IN-PrabhatNeural',
    'English (Ireland)', 'en-IE', 'Female', 'en-IE-EmilyNeural',
    'English (Ireland)', 'en-IE', 'Male', 'en-IE-ConnorNeural',
    'English (Philippines)', 'en-PH', 'Female', 'en-PH-RosaNeural',
    'English (Philippines)', 'en-PH', 'Male', 'en-PH-JamesNeural',
    'English (United Kingdom)', 'en-GB', 'Female', 'en-GB-LibbyNeural',
    'English (United Kingdom)', 'en-GB', 'Female', 'en-GB-MiaNeural',
    'English (United Kingdom)', 'en-GB', 'Male', 'en-GB-RyanNeural',
    'English (United States)', 'en-US', 'Female', 'en-US-AriaNeural',
    'English (United States)', 'en-US', 'Female', 'en-US-JennyNeural',
    'English (United States)', 'en-US', 'Male', 'en-US-GuyNeural',
    'Estonian (Estonia)', 'et-EE', 'Female', 'et-EE-AnuNeural',
    'Estonian (Estonia)', 'et-EE', 'Male', 'et-EE-KertNeural',
    'Finnish (Finland)', 'fi-FI', 'Female', 'fi-FI-NooraNeural',
    'Finnish (Finland)', 'fi-FI', 'Female', 'fi-FI-SelmaNeural',
    'Finnish (Finland)', 'fi-FI', 'Male', 'fi-FI-HarriNeural',
    'French (Belgium)', 'fr-BE', 'Female', 'fr-BE-CharlineNeural',
    'French (Belgium)', 'fr-BE', 'Male', 'fr-BE-GerardNeural',
    'French (Canada)', 'fr-CA', 'Female', 'fr-CA-SylvieNeural',
    'French (Canada)', 'fr-CA', 'Male', 'fr-CA-AntoineNeural',
    'French (Canada)', 'fr-CA', 'Male', 'fr-CA-JeanNeural',
    'French (France)', 'fr-FR', 'Female', 'fr-FR-DeniseNeural',
    'French (France)', 'fr-FR', 'Male', 'fr-FR-HenriNeural',
    'French (Switzerland)', 'fr-CH', 'Female', 'fr-CH-ArianeNeural',
    'French (Switzerland)', 'fr-CH', 'Male', 'fr-CH-FabriceNeural',
    'German (Austria)', 'de-AT', 'Female', 'de-AT-IngridNeural',
    'German (Austria)', 'de-AT', 'Male', 'de-AT-JonasNeural',
    'German (Germany)', 'de-DE', 'Female', 'de-DE-KatjaNeural',
    'German (Germany)', 'de-DE', 'Male', 'de-DE-ConradNeural',
    'German (Switzerland)', 'de-CH', 'Female', 'de-CH-LeniNeural',
    'German (Switzerland)', 'de-CH', 'Male', 'de-CH-JanNeural',
    'Greek (Greece)', 'el-GR', 'Female', 'el-GR-AthinaNeural',
    'Greek (Greece)', 'el-GR', 'Male', 'el-GR-NestorasNeural',
    'Hebrew (Israel)', 'he-IL', 'Female', 'he-IL-HilaNeural',
    'Hebrew (Israel)', 'he-IL', 'Male', 'he-IL-AvriNeural',
    'Hindi (India)', 'hi-IN', 'Female', 'hi-IN-SwaraNeural',
    'Hindi (India)', 'hi-IN', 'Male', 'hi-IN-MadhurNeural',
    'Hungarian (Hungary)', 'hu-HU', 'Female', 'hu-HU-NoemiNeural',
    'Hungarian (Hungary)', 'hu-HU', 'Male', 'hu-HU-TamasNeural',
    'Indonesian (Indonesia)', 'id-ID', 'Female', 'id-ID-GadisNeural',
    'Indonesian (Indonesia)', 'id-ID', 'Male', 'id-ID-ArdiNeural',
    'Irish (Ireland)', 'ga-IE', 'Female', 'ga-IE-OrlaNeural',
    'Irish (Ireland)', 'ga-IE', 'Male', 'ga-IE-ColmNeural',
    'Italian (Italy)', 'it-IT', 'Female', 'it-IT-ElsaNeural',
    'Italian (Italy)', 'it-IT', 'Female', 'it-IT-IsabellaNeural',
    'Italian (Italy)', 'it-IT', 'Male', 'it-IT-DiegoNeural',
    'Japanese (Japan)', 'ja-JP', 'Female', 'ja-JP-NanamiNeural',
    'Japanese (Japan)', 'ja-JP', 'Male', 'ja-JP-KeitaNeural',
    'Korean (Korea)', 'ko-KR', 'Female', 'ko-KR-SunHiNeural',
    'Korean (Korea)', 'ko-KR', 'Male', 'ko-KR-InJoonNeural',
    'Latvian (Latvia)', 'lv-LV', 'Female', 'lv-LV-EveritaNeural',
    'Latvian (Latvia)', 'lv-LV', 'Male', 'lv-LV-NilsNeural',
    'Lithuanian (Lithuania)', 'lt-LT', 'Female', 'lt-LT-OnaNeural',
    'Lithuanian (Lithuania)', 'lt-LT', 'Male', 'lt-LT-LeonasNeural',
    'Malay (Malaysia)', 'ms-MY', 'Female', 'ms-MY-YasminNeural',
    'Malay (Malaysia)', 'ms-MY', 'Male', 'ms-MY-OsmanNeural',
    'Maltese (Malta)', 'mt-MT', 'Female', 'mt-MT-GraceNeural',
    'Maltese (Malta)', 'mt-MT', 'Male', 'mt-MT-JosephNeural',
    'Norwegian (Bokmål,Norway)', 'nb-NO', 'Female', 'nb-NO-IselinNeural',
    'Norwegian (Bokmål,Norway)', 'nb-NO', 'Female', 'nb-NO-PernilleNeural',
    'Norwegian (Bokmål,Norway)', 'nb-NO', 'Male', 'nb-NO-FinnNeural',
    'Polish (Poland)', 'pl-PL', 'Female', 'pl-PL-AgnieszkaNeural',
    'Polish (Poland)', 'pl-PL', 'Female', 'pl-PL-ZofiaNeural',
    'Polish (Poland)', 'pl-PL', 'Male', 'pl-PL-MarekNeural',
    'Portuguese (Brazil)', 'pt-BR', 'Female', 'pt-BR-FranciscaNeural',
    'Portuguese (Brazil)', 'pt-BR', 'Male', 'pt-BR-AntonioNeural',
    'Portuguese (Portugal)', 'pt-PT', 'Female', 'pt-PT-FernandaNeural',
    'Portuguese (Portugal)', 'pt-PT', 'Female', 'pt-PT-RaquelNeural',
    'Portuguese (Portugal)', 'pt-PT', 'Male', 'pt-PT-DuarteNeural',
    'Romanian (Romania)', 'ro-RO', 'Female', 'ro-RO-AlinaNeural',
    'Romanian (Romania)', 'ro-RO', 'Male', 'ro-RO-EmilNeural',
    'Russian (Russia)', 'ru-RU', 'Female', 'ru-RU-DariyaNeural',
    'Russian (Russia)', 'ru-RU', 'Female', 'ru-RU-SvetlanaNeural',
    'Russian (Russia)', 'ru-RU', 'Male', 'ru-RU-DmitryNeural',
    'Slovak (Slovakia)', 'sk-SK', 'Female', 'sk-SK-ViktoriaNeural',
    'Slovak (Slovakia)', 'sk-SK', 'Male', 'sk-SK-LukasNeural',
    'Slovenian (Slovenia)', 'sl-SI', 'Female', 'sl-SI-PetraNeural',
    'Slovenian (Slovenia)', 'sl-SI', 'Male', 'sl-SI-RokNeural',
    'Spanish (Mexico)', 'es-MX', 'Female', 'es-MX-DaliaNeural',
    'Spanish (Mexico)', 'es-MX', 'Male', 'es-MX-JorgeNeural',
    'Spanish (Spain)', 'es-ES', 'Female', 'es-ES-ElviraNeural',
    'Spanish (Spain)', 'es-ES', 'Male', 'es-ES-AlvaroNeural',
    'Swedish (Sweden)', 'sv-SE', 'Female', 'sv-SE-HilleviNeural',
    'Swedish (Sweden)', 'sv-SE', 'Female', 'sv-SE-SofieNeural',
    'Swedish (Sweden)', 'sv-SE', 'Male', 'sv-SE-MattiasNeural',
    'Tamil (India)', 'ta-IN', 'Female', 'ta-IN-PallaviNeural',
    'Tamil (India)', 'ta-IN', 'Male', 'ta-IN-ValluvarNeural',
    'Telugu (India)', 'te-IN', 'Female', 'te-IN-ShrutiNeural',
    'Telugu (India)', 'te-IN', 'Male', 'te-IN-MohanNeural',
    'Thai (Thailand)', 'th-TH', 'Female', 'th-TH-AcharaNeural',
    'Thai (Thailand)', 'th-TH', 'Female', 'th-TH-PremwadeeNeural',
    'Thai (Thailand)', 'th-TH', 'Male', 'th-TH-NiwatNeural',
    'Turkish (Turkey)', 'tr-TR', 'Female', 'tr-TR-EmelNeural',
    'Turkish (Turkey)', 'tr-TR', 'Male', 'tr-TR-AhmetNeural',
    'Ukrainian (Ukraine)', 'uk-UA', 'Female', 'en-ZA-LeahNeural',
    'Ukrainian (Ukraine)', 'uk-UA', 'Male', 'en-ZA-LukeNeural',
    'Urdu (Pakistan)', 'ur-PK', 'Female', 'uk-UA-PolinaNeural',
    'Urdu (Pakistan)', 'ur-PK', 'Male', 'uk-UA-OstapNeural',
    'Vietnamese (Vietnam)', 'vi-VN', 'Female', 'vi-VN-HoaiMyNeural',
    'Vietnamese (Vietnam)', 'vi-VN', 'Male', 'vi-VN-NamMinhNeural',
    'Welsh (UK)', 'cy-GB', 'Female', 'cy-GB-NiaNeural',
    'Welsh (UK)', 'cy-GB', 'Male', 'cy-GB-AledNeural',
], 4).map(([label, code, gender, ssmlName]) => ({ label, locale: code, gender, voice: ssmlName }))